### ISSUE TITLE
Method App\Http\Controllers\PaiementController::requestPayment does not exist.

### ISSUE THREAD

**Issue by abdellatif-laghjaj** [combindma/cmi-payment#2]
Hello i got this error
because u didnt give us how to implement the requestPayment method !!

![image](https://github.com/combindma/cmi-payment/assets/79521157/ac436aca-7f2e-4d45-b16e-22d661dcf85c)

**Comment by omarherri** [comment]
In order this to work you need to add the trait `CmiGateway` to your controller. After that you can call the `requestPayment() `method.
